/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pub2.mvc;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class ViewMeseAdmin extends javax.swing.JFrame{

    /**
     * Creates new form ViewMeseAdmin
     */
    public ViewMeseAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonAdaugareMasa = new javax.swing.JButton();
        campNumar = new javax.swing.JTextField();
        butonModStergere = new javax.swing.JButton();
        butonGestionareUtilizatori = new javax.swing.JButton();
        butonGestionareProduse = new javax.swing.JButton();
        butonRaport = new javax.swing.JButton();
        panou = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butonAdaugareMasa.setText("adauga masa");
        butonAdaugareMasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAdaugareMasaActionPerformed(evt);
            }
        });

        butonModStergere.setText("mod stergere");
        butonModStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonModStergereActionPerformed(evt);
            }
        });

        butonGestionareUtilizatori.setText("gestioneaza utilizatori");
        butonGestionareUtilizatori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonGestionareUtilizatoriActionPerformed(evt);
            }
        });

        butonGestionareProduse.setText("gestioneaza produse");
        butonGestionareProduse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonGestionareProduseActionPerformed(evt);
            }
        });

        butonRaport.setText("genereaza raport");
        butonRaport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonRaportActionPerformed(evt);
            }
        });

        panou.setBackground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout panouLayout = new javax.swing.GroupLayout(panou);
        panou.setLayout(panouLayout);
        panouLayout.setHorizontalGroup(
            panouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        panouLayout.setVerticalGroup(
            panouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butonModStergere, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butonAdaugareMasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campNumar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(butonGestionareUtilizatori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonGestionareProduse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonRaport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campNumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonAdaugareMasa))
                        .addGap(18, 18, 18)
                        .addComponent(butonModStergere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butonGestionareUtilizatori)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butonGestionareProduse)
                        .addGap(18, 18, 18)
                        .addComponent(butonRaport))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonAdaugareMasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAdaugareMasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonAdaugareMasaActionPerformed

    private void butonModStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonModStergereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonModStergereActionPerformed

    private void butonGestionareUtilizatoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonGestionareUtilizatoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonGestionareUtilizatoriActionPerformed

    private void butonGestionareProduseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonGestionareProduseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonGestionareProduseActionPerformed

    private void butonRaportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonRaportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonRaportActionPerformed

    public JButton getButonAdaugareMasa() {
        return butonAdaugareMasa;
    }

    public JButton getButonGestionareProduse() {
        return butonGestionareProduse;
    }

    public JButton getButonGestionareUtilizatori() {
        return butonGestionareUtilizatori;
    }

    public JButton getButonRaport() {
        return butonRaport;
    }
    
    public JButton getButonModStergere() {
        return butonModStergere;
    }
    
    public JTextField getCampNumar() {
        return campNumar;
    }
    
    public JPanel getPanou(){
        return panou;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMeseAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMeseAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMeseAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMeseAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMeseAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonAdaugareMasa;
    private javax.swing.JButton butonGestionareProduse;
    private javax.swing.JButton butonGestionareUtilizatori;
    private javax.swing.JButton butonModStergere;
    private javax.swing.JButton butonRaport;
    private javax.swing.JTextField campNumar;
    private javax.swing.JPanel panou;
    // End of variables declaration//GEN-END:variables
}
